"""Tests for provenance system.

Validates:
- Activity recording works
- Entity generation links to activity
- No orphan entities (all entities have generation record)
"""

import pytest
from sqlalchemy import create_engine, select
from sqlalchemy.orm import sessionmaker

from islam_intelligent.domain.models import Base
from islam_intelligent.provenance.models import (
    ProvActivity,
    ProvEntity,
    ProvGeneration,
)
from islam_intelligent.provenance.recorder import (
    compute_params_hash,
    get_git_sha,
    record_activity,
    record_generation,
)


@pytest.fixture
def db_session():
    """Create a fresh in-memory database session for each test."""
    engine = create_engine("sqlite+pysqlite:///:memory:", future=True)
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine, future=True)
    session = Session()
    yield session
    session.close()


class TestGitShaDetection:
    """Tests for git SHA auto-detection."""

    def test_get_git_sha_returns_string_or_none(self):
        """Git SHA should be 40-char hex string or None if not in git repo."""
        sha = get_git_sha()

        if sha is not None:
            assert len(sha) == 40
            assert all(c in "0123456789abcdef" for c in sha)


class TestParamsHash:
    """Tests for parameter hash computation."""

    def test_compute_params_hash_returns_64_char_hex(self):
        """Params hash should be 64-character hex string."""
        params = {"key": "value", "number": 42}
        hash_value = compute_params_hash(params)

        assert len(hash_value) == 64
        assert all(c in "0123456789abcdef" for c in hash_value)

    def test_compute_params_hash_is_deterministic(self):
        """Same params should produce same hash."""
        params = {"b": 2, "a": 1}  # Note: different order
        hash1 = compute_params_hash(params)
        hash2 = compute_params_hash({"a": 1, "b": 2})

        assert hash1 == hash2

    def test_compute_params_hash_different_params_different_hash(self):
        """Different params should produce different hashes."""
        hash1 = compute_params_hash({"key": "value1"})
        hash2 = compute_params_hash({"key": "value2"})

        assert hash1 != hash2


class TestActivityRecording:
    """Tests for activity recording functionality."""

    def test_record_activity_creates_activity(self, db_session):
        """record_activity should create and return a ProvActivity."""
        activity = record_activity(
            session=db_session,
            activity_type="test.activity",
            params={"param1": "value1"},
        )
        db_session.commit()

        assert activity.activity_id is not None
        assert activity.activity_type == "test.activity"
        assert activity.params_hash is not None
        assert activity.started_at is not None

    def test_record_activity_with_explicit_id(self, db_session):
        """record_activity should use explicit activity_id if provided."""
        explicit_id = "my-custom-activity-id"
        activity = record_activity(
            session=db_session,
            activity_type="test.activity",
            activity_id=explicit_id,
        )
        db_session.commit()

        assert activity.activity_id == explicit_id

    def test_record_activity_without_params(self, db_session):
        """record_activity should work without params."""
        activity = record_activity(
            session=db_session,
            activity_type="test.activity",
        )
        db_session.commit()

        assert activity.activity_type == "test.activity"
        assert activity.params_hash is None


class TestEntityGeneration:
    """Tests for entity generation linking."""

    def test_record_generation_creates_entity_and_generation(self, db_session):
        """record_generation should create entity with generation link."""
        # First create an activity
        activity = record_activity(
            session=db_session,
            activity_type="test.etl",
        )
        db_session.commit()

        # Create entity generated by activity
        entity, generation = record_generation(
            session=db_session,
            entity_id="dataset-001",
            activity_id=activity.activity_id,
            entity_type="dataset",
            label="Test Dataset",
            json_data={"rows": 1000},
        )
        db_session.commit()

        # Verify entity
        assert entity.entity_id == "dataset-001"
        assert entity.entity_type == "dataset"
        assert entity.label == "Test Dataset"

        # Verify generation link
        assert generation.entity_id == "dataset-001"
        assert generation.activity_id == activity.activity_id

    def test_record_generation_raises_on_missing_activity(self, db_session):
        """record_generation should raise ValueError for non-existent activity."""
        with pytest.raises(ValueError, match="Activity non-existent not found"):
            record_generation(
                session=db_session,
                entity_id="dataset-001",
                activity_id="non-existent",
                entity_type="dataset",
            )

    def test_entity_generation_relationship(self, db_session):
        """Entity should be linked to activity via generation relationship."""
        # Create activity
        activity = record_activity(
            session=db_session,
            activity_type="test.etl",
        )
        db_session.commit()

        # Create entity
        entity, _ = record_generation(
            session=db_session,
            entity_id="dataset-002",
            activity_id=activity.activity_id,
            entity_type="dataset",
        )
        db_session.commit()

        # Query and verify relationship
        stmt = select(ProvEntity).where(ProvEntity.entity_id == "dataset-002")
        result = db_session.execute(stmt).scalar_one()

        assert len(result.generated_by) == 1
        assert result.generated_by[0].activity_id == activity.activity_id


class TestOrphanDetection:
    """Tests for orphan entity detection - entities without generation records."""

    def test_no_orphans_when_all_entities_have_generation(self, db_session):
        """All properly created entities should have generation records."""
        # Create activity
        activity = record_activity(
            session=db_session,
            activity_type="test.etl",
        )
        db_session.commit()

        # Create entities via record_generation (proper method)
        for i in range(3):
            record_generation(
                session=db_session,
                entity_id=f"entity-{i}",
                activity_id=activity.activity_id,
                entity_type="test",
            )
        db_session.commit()

        # Count entities without generation (should be 0)
        stmt = (
            select(ProvEntity)
            .outerjoin(ProvGeneration, ProvEntity.entity_id == ProvGeneration.entity_id)
            .where(ProvGeneration.entity_id.is_(None))
        )

        orphans = db_session.execute(stmt).scalars().all()
        assert len(orphans) == 0

    def test_detect_orphan_entities(self, db_session):
        """Direct entity creation without generation should create orphans."""
        # Create an entity directly (bypassing record_generation)
        orphan = ProvEntity(
            entity_id="orphan-entity",
            entity_type="test",
            label="Orphan Entity",
        )
        db_session.add(orphan)
        db_session.commit()

        # Count entities without generation
        stmt = (
            select(ProvEntity)
            .outerjoin(ProvGeneration, ProvEntity.entity_id == ProvGeneration.entity_id)
            .where(ProvGeneration.entity_id.is_(None))
        )

        orphans = db_session.execute(stmt).scalars().all()
        assert len(orphans) == 1
        assert orphans[0].entity_id == "orphan-entity"

    def test_mixed_orphans_and_valid_entities(self, db_session):
        """System should correctly identify orphans among valid entities."""
        # Create activity and valid entities
        activity = record_activity(
            session=db_session,
            activity_type="test.etl",
        )
        db_session.commit()

        record_generation(
            session=db_session,
            entity_id="valid-entity",
            activity_id=activity.activity_id,
            entity_type="test",
        )
        db_session.commit()

        # Create orphan directly
        orphan = ProvEntity(
            entity_id="orphan-entity-2",
            entity_type="test",
        )
        db_session.add(orphan)
        db_session.commit()

        # Find orphans
        stmt = (
            select(ProvEntity)
            .outerjoin(ProvGeneration, ProvEntity.entity_id == ProvGeneration.entity_id)
            .where(ProvGeneration.entity_id.is_(None))
        )

        orphans = db_session.execute(stmt).scalars().all()
        assert len(orphans) == 1
        assert orphans[0].entity_id == "orphan-entity-2"


class TestIntegration:
    """Integration tests for full provenance workflow."""

    def test_full_provenance_chain(self, db_session):
        """Test a complete provenance chain: activity → entity generation."""
        # Record ingestion activity
        activity = record_activity(
            session=db_session,
            activity_type="etl.ingest",
            params={
                "source": "quran.com",
                "surah_range": [1, 114],
            },
        )
        db_session.commit()

        # Generate entity
        entity, generation = record_generation(
            session=db_session,
            entity_id="quran-corpus-v1",
            activity_id=activity.activity_id,
            entity_type="corpus",
            label="Quran Text Corpus",
            json_data={"verses": 6236, "language": "ar"},
        )
        db_session.commit()

        # Verify full chain
        assert activity.params_hash is not None
        assert generation.generated_at is not None

        # Query back and verify
        stmt = select(ProvActivity).where(
            ProvActivity.activity_id == activity.activity_id
        )
        stored_activity = db_session.execute(stmt).scalar_one()

        assert len(stored_activity.generated) == 1
        assert stored_activity.generated[0].entity_id == "quran-corpus-v1"
