"""HyDE (Hypothetical Document Embeddings) for query expansion.

This module implements the HyDE technique where:
1. Generate a hypothetical answer using an LLM
2. Embed the hypothetical answer (not the original query)
3. Use the hypothetical embedding for retrieval

The implementation is fail-safe and gracefully falls back to query-only embeddings
when the LLM is unavailable or disabled.

References:
- Gao et al. "Precise Zero-Shot Dense Retrieval without Relevance Labels"
  https://arxiv.org/abs/2212.10496
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass

from ...config import settings
from .embeddings import EmbeddingGenerator

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class HyDEConfig:
    """Configuration for HyDE query expansion."""

    enabled: bool = True
    max_tokens: int = 150
    temperature: float = 0.3
    model: str = "gpt-4o-mini"
    seed: int = 42


class HyDEQueryExpander:
    """Expand queries using HyDE: generate hypothetical answers for better retrieval.

    The HyDE technique improves retrieval by:
    1. Using an LLM to generate a hypothetical answer to the query
    2. Embedding that hypothetical answer instead of the query itself
    3. Retrieving documents similar to the hypothetical answer

    This works because hypothetical answers often contain richer semantic content
    and domain terminology than the original query.

    Example:
        >>> expander = HyDEQueryExpander()
        >>> hypothetical = expander.expand("How to pray tahajjud?")
        >>> print(hypothetical)
        'Tahajjud prayer is performed after sleeping and before Fajr...'
        >>> embedding = expander.get_embedding("How to pray tahajjud?")
        # Returns embedding of hypothetical answer, not the query
    """

    config: HyDEConfig
    api_key: str | None
    base_url: str | None
    _available: bool
    _client: object | None
    _embedding_generator: EmbeddingGenerator

    def __init__(
        self,
        config: HyDEConfig | None = None,
        embedding_generator: EmbeddingGenerator | None = None,
        api_key: str | None = None,
        base_url: str | None = None,
    ) -> None:
        """Initialize the HyDE query expander.

        Args:
            config: HyDE configuration. Uses defaults if not provided.
            embedding_generator: Embedding generator instance. Creates new one if not provided.
            api_key: OpenAI API key. Falls back to OPENAI_API_KEY env var.
            base_url: Custom OpenAI-compatible API base URL.
        """
        self.config = config or HyDEConfig()
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        self._embedding_generator = embedding_generator or EmbeddingGenerator()

        raw_base_url = (
            base_url or os.getenv("RAG_LLM_BASE_URL") or os.getenv("OPENAI_BASE_URL")
        )
        self.base_url = (
            raw_base_url.strip()
            if isinstance(raw_base_url, str) and raw_base_url.strip()
            else None
        )

        self._client = None
        self._available = False

        # Only initialize LLM client if HyDE is enabled
        if not self.config.enabled:
            logger.debug("HyDE disabled by configuration")
            return

        if not self.api_key:
            logger.debug("HyDE LLM unavailable: no API key")
            return

        key = self.api_key

        try:
            from openai import OpenAI

            if self.base_url:
                self._client = OpenAI(
                    api_key=key,
                    base_url=self.base_url,
                    max_retries=2,
                    timeout=30.0,
                )
            else:
                self._client = OpenAI(
                    api_key=key,
                    max_retries=2,
                    timeout=30.0,
                )
            self._available = True
            logger.debug("HyDE LLM client initialized successfully")
        except ImportError:
            logger.warning("OpenAI SDK not installed; HyDE expansion disabled")

    def is_available(self) -> bool:
        """Check if HyDE expansion is available (enabled and LLM ready)."""
        return self.config.enabled and self._available and self._client is not None

    def expand(self, query: str) -> str:
        """Generate a hypothetical answer for the query.

        Args:
            query: The original user query.

        Returns:
            A hypothetical answer generated by the LLM, or the original query
            if HyDE is unavailable or disabled.

        Raises:
            RuntimeError: If LLM is unavailable and strict mode is enabled.
        """
        if not self.is_available():
            logger.debug("HyDE unavailable, returning original query")
            return query

        client = self._client
        if client is None:
            return query

        prompt = self._build_hypothetical_prompt(query)

        try:
            chat = getattr(client, "chat", None)
            completions = getattr(chat, "completions", None)
            create = getattr(completions, "create", None)
            if create is None or not callable(create):
                logger.warning("OpenAI client does not expose chat.completions.create")
                return query

            response = create(
                model=self.config.model,
                messages=[
                    {"role": "system", "content": self._system_prompt()},
                    {"role": "user", "content": prompt},
                ],
                temperature=self.config.temperature,
                max_tokens=self.config.max_tokens,
                seed=self.config.seed,
            )

            choices = getattr(response, "choices", [])
            if not choices:
                logger.warning("HyDE LLM returned empty choices")
                return query

            message = getattr(choices[0], "message", None)
            content = str(getattr(message, "content", "") or "").strip()

            if not content:
                logger.warning("HyDE LLM returned empty content")
                return query

            logger.debug("HyDE generated hypothetical answer: %r", content[:100])
            return content

        except Exception as exc:
            logger.warning("HyDE generation failed, falling back to query: %s", exc)
            return query

    def get_embedding(self, query: str) -> list[float]:
        """Get embedding for retrieval using HyDE expansion.

        This method:
        1. Generates a hypothetical answer to the query
        2. Embeds the hypothetical answer (not the original query)
        3. Returns the embedding for use in vector retrieval

        Args:
            query: The original user query.

        Returns:
            Embedding vector for the hypothetical answer, or query embedding
            if HyDE is unavailable.
        """
        # Generate hypothetical answer
        hypothetical = self.expand(query)

        # If we got back the original query (HyDE failed/unavailable),
        # use the original query for embedding
        text_to_embed = hypothetical if hypothetical != query else query

        # Generate embedding
        embedding = self._embedding_generator.generate_embedding(text_to_embed)

        logger.debug(
            "HyDE embedding generated for %s (hypothetical length: %d)",
            "hypothetical answer" if hypothetical != query else "original query",
            len(text_to_embed),
        )

        return embedding

    def get_embedding_with_fallback(
        self, query: str
    ) -> tuple[list[float], dict[str, object]]:
        """Get embedding with metadata about whether HyDE was used.

        Args:
            query: The original user query.

        Returns:
            Tuple of (embedding vector, metadata dict).
            Metadata includes:
                - 'hyde_used': Whether HyDE expansion was applied
                - 'hypothetical_answer': The generated hypothetical answer (if used)
                - 'text_embedded': The actual text that was embedded
        """
        hypothetical = self.expand(query)
        used_hyde = hypothetical != query
        text_to_embed = hypothetical if used_hyde else query

        embedding = self._embedding_generator.generate_embedding(text_to_embed)

        metadata: dict[str, object] = {
            "hyde_used": used_hyde,
            "text_embedded": text_to_embed,
        }

        if used_hyde:
            metadata["hypothetical_answer"] = hypothetical

        return embedding, metadata

    def _system_prompt(self) -> str:
        """System prompt for hypothetical answer generation."""
        return (
            "You are a knowledgeable Islamic scholar. "
            "Given a question, provide a brief, factual hypothetical answer "
            "that captures the key concepts and terminology that would appear "
            "in authoritative Islamic sources. Answer concisely in 2-3 sentences."
        )

    def _build_hypothetical_prompt(self, query: str) -> str:
        """Build the prompt for generating a hypothetical answer."""
        return (
            f"Question: {query}\n\n"
            "Provide a brief hypothetical answer that would be found in "
            "Islamic sources (Quran, Hadith, or scholarly works). "
            "Include relevant Arabic terms and key concepts. "
            "Keep it factual and concise."
        )


def create_hyde_expander(
    enabled: bool | None = None,
    max_tokens: int = 150,
    temperature: float = 0.3,
) -> HyDEQueryExpander:
    """Factory function to create a configured HyDE expander.

    Args:
        enabled: Whether HyDE is enabled. Falls back to RAG_ENABLE_HYDE env var
            or defaults to True if not set.
        max_tokens: Maximum tokens for hypothetical answer generation.
        temperature: Temperature for LLM generation.

    Returns:
        Configured HyDEQueryExpander instance.
    """
    # Determine if HyDE should be enabled
    if enabled is None:
        raw = os.getenv("RAG_ENABLE_HYDE", "true").lower()
        enabled = raw in ("1", "true", "yes", "on")

    config = HyDEConfig(
        enabled=enabled,
        max_tokens=max_tokens,
        temperature=temperature,
        model=settings.rag_llm_model,
        seed=settings.rag_llm_seed,
    )

    return HyDEQueryExpander(config=config)


__all__ = [
    "HyDEQueryExpander",
    "HyDEConfig",
    "create_hyde_expander",
]
