"""Provenance recorder helper for tracking data lineage.

Provides high-level APIs for recording activities, entity generation,
and computing provenance metadata like git SHAs and parameter hashes.
"""

import hashlib
import json
import subprocess
from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy.orm import Session

from .models import (
    ProvActivity,
    ProvEntity,
    ProvGeneration,
)

from .hash_chain import (
    compute_activity_hash,
    find_prev_activity_hash,
    get_activity_io_hashes,
)


def get_git_sha() -> str | None:
    """Get the current git commit hash.

    Automatically detects the git commit hash from the repository.
    Returns None if git is not available or not in a git repository.

    Returns:
        The 40-character git SHA hash, or None if unavailable.
    """
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
            timeout=5,
        )
        sha = result.stdout.strip()
        # Validate it's a proper SHA (40 hex characters)
        if len(sha) == 40 and all(c in "0123456789abcdef" for c in sha.lower()):
            return sha.lower()
        return None
    except (subprocess.SubprocessError, FileNotFoundError, subprocess.TimeoutExpired):
        return None


def compute_params_hash(params: dict[str, object]) -> str:
    """Compute a SHA-256 hash of canonical JSON parameters.

    This creates a deterministic hash for tracking parameter changes.
    The parameters are serialized to JSON with sorted keys for consistency.

    Args:
        params: Dictionary of parameters to hash.

    Returns:
        64-character hexadecimal SHA-256 hash.
    """
    # Serialize to canonical JSON (sorted keys, no extra whitespace)
    canonical_json = json.dumps(params, sort_keys=True, separators=(",", ":"))
    # Compute SHA-256 hash
    hash_bytes = hashlib.sha256(canonical_json.encode("utf-8")).digest()
    return hash_bytes.hex()


def record_activity(
    session: Session,
    activity_type: str,
    params: dict[str, object] | None = None,
    git_sha: str | None = None,
    activity_id: str | None = None,
) -> ProvActivity:
    """Record a new provenance activity.

    Activities represent operations that generate or transform entities.
    They capture when something happened, what code version was used,
    and what parameters were passed.

    Args:
        session: SQLAlchemy database session.
        activity_type: Type/category of activity (e.g., "etl.ingest", "model.train").
        params: Optional dictionary of activity parameters.
        git_sha: Optional git commit hash. If None, auto-detected via get_git_sha().
        activity_id: Optional explicit activity ID. If None, auto-generated UUID.

    Returns:
        The created ProvActivity instance (not yet committed).
    """
    if activity_id is None:
        activity_id = str(uuid4())

    if git_sha is None:
        git_sha = get_git_sha()

    params_hash = None
    if params is not None:
        params_hash = compute_params_hash(params)

    activity = ProvActivity(
        activity_id=activity_id,
        activity_type=activity_type,
        started_at=datetime.now(timezone.utc),
        git_sha=git_sha,
        params_hash=params_hash,
    )

    session.add(activity)
    return activity


def record_generation(
    session: Session,
    entity_id: str,
    activity_id: str,
    entity_type: str,
    label: str | None = None,
    json_data: dict[str, object] | None = None,
) -> tuple[ProvEntity, ProvGeneration]:
    """Record that an entity was generated by an activity.

    This creates both the entity record and the generation link
    connecting it to the activity that produced it.

    Args:
        session: SQLAlchemy database session.
        entity_id: Unique identifier for the entity.
        activity_id: ID of the activity that generated this entity.
        entity_type: Type/category of entity (e.g., "dataset", "model", "report").
        label: Optional human-readable label/description.
        json_data: Optional JSON-serializable data associated with the entity.

    Returns:
        Tuple of (ProvEntity, ProvGeneration) instances (not yet committed).

    Raises:
        ValueError: If the referenced activity does not exist.
    """
    # Verify activity exists
    activity = session.get(ProvActivity, activity_id)
    if activity is None:
        raise ValueError(f"Activity {activity_id} not found")

    # Create entity
    entity = ProvEntity(
        entity_id=entity_id,
        entity_type=entity_type,
        label=label,
        json_data=json.dumps(
            json_data, sort_keys=True, separators=(",", ":"), ensure_ascii=True
        )
        if json_data
        else None,
    )
    session.add(entity)

    # Create generation record
    generation = ProvGeneration(
        entity_id=entity_id,
        activity_id=activity_id,
    )
    session.add(generation)

    return entity, generation


def finish_activity(session: Session, activity: ProvActivity) -> None:
    """Mark an activity as completed.

    Updates the activity's ended_at timestamp to the current time.

    Args:
        session: SQLAlchemy database session.
        activity: The activity to mark as finished.
    """
    if activity.ended_at is None:
        activity.ended_at = datetime.now(timezone.utc)

    # Compute hash chain once the activity is complete and I/O relationships exist.
    if activity.activity_hash is None:
        prev_hash = find_prev_activity_hash(session, activity)
        input_hashes, output_hashes = get_activity_io_hashes(
            session, activity.activity_id
        )
        activity.prev_activity_hash = prev_hash
        activity.activity_hash = compute_activity_hash(
            activity,
            input_hashes=input_hashes,
            output_hashes=output_hashes,
            prev_activity_hash=prev_hash,
        )

    session.add(activity)


def record_usage(
    session: Session,
    activity_id: str,
    entity_id: str,
) -> None:
    """Record that an activity used an entity.

    This is a lower-level function for explicit usage tracking.
    Most usage is implicitly tracked via derivation relationships.

    Args:
        session: SQLAlchemy database session.
        activity_id: ID of the activity that used the entity.
        entity_id: ID of the entity that was used.

    Raises:
        ValueError: If the activity or entity does not exist.
    """
    from .models import ProvUsage

    # Verify both exist
    activity = session.get(ProvActivity, activity_id)
    if activity is None:
        raise ValueError(f"Activity {activity_id} not found")

    entity = session.get(ProvEntity, entity_id)
    if entity is None:
        raise ValueError(f"Entity {entity_id} not found")

    usage = ProvUsage(
        activity_id=activity_id,
        entity_id=entity_id,
    )
    session.add(usage)


def record_derivation(
    session: Session,
    derived_entity_id: str,
    source_entity_id: str,
    activity_id: str | None = None,
) -> None:
    """Record that one entity was derived from another.

    Derivation tracks lineage - understanding how data flows through
    the system from source to derived outputs.

    Args:
        session: SQLAlchemy database session.
        derived_entity_id: ID of the derived (output) entity.
        source_entity_id: ID of the source (input) entity.
        activity_id: Optional ID of the activity that performed the derivation.

    Raises:
        ValueError: If the entities do not exist.
    """
    from .models import ProvDerivation

    # Verify entities exist
    derived = session.get(ProvEntity, derived_entity_id)
    if derived is None:
        raise ValueError(f"Derived entity {derived_entity_id} not found")

    source = session.get(ProvEntity, source_entity_id)
    if source is None:
        raise ValueError(f"Source entity {source_entity_id} not found")

    # Verify activity if provided
    if activity_id is not None:
        activity = session.get(ProvActivity, activity_id)
        if activity is None:
            raise ValueError(f"Activity {activity_id} not found")

    derivation = ProvDerivation(
        derived_entity_id=derived_entity_id,
        source_entity_id=source_entity_id,
        activity_id=activity_id,
    )
    session.add(derivation)
